### ISSUE TITLE
rust grpc 调研

### ISSUE THREAD

**Issue by lishulong** [openacid/celeritasdb#103]
**Is your feature request related to a problem? Please describe.**
希望使用更简洁的方式处理各个节点之间的通信。
候选方案有socket和grpc，从其中选择更优的方案。

**Describe the solution you'd like**
如果grpc能够支持更简洁的方式支持长连接，那么选择grpc。

- 方便的建立连接

- 能够方便的丢弃其中的完整或者残存数据，不至于影响下一个rpc

**Describe alternatives you've considered**
socket

**Additional context**

**Comment by drmingdrmer** [comment]
目前理解的是grpc用http2 做传输协议. 一个请求一个http请求, 所以应该在http那层就处理了包完整性的问题了

**Comment by drmingdrmer** [comment]
目前基本确定用prost + tonic 来实现grpc了, 剩下的是在grpc基础上实现复制, 此issue是否可关? @lishulong
