### ISSUE TITLE
目录结构

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/celeritasdb#14]
### 需求

- 整个项目可能需要编译出多个binary(一个server, 一个mgr等等).
- 每个组件可能需要拆分到多个repo中, 也可能需要以源码方式(或fork然后修改过的源码方式)引入第三方的repo.

### 设计

顶级一个workspace, 指定下面的几个binary和lib作为members.

以源码方式引入的repo, 手动clone进来(不知道rust有没有好的包管理方式? git-submodule可以做这个事情, 但命令需要学习一下).

`/Cargo.toml`:

```
[workspace]

members = [
    "cele",
    "mgr", 
]
```

目录结构:

```
celeritas/
▾ cele/
  ▾ src/
      main.rs
    Cargo.toml
▾ mgr/
  ▾ src/
      main.rs
    Cargo.toml
  Cargo.toml
```

**Comment by lishulong** [comment]
（1）rust 的包管理可以指定版本和nightly build之类的，感觉不需要额外引入git-submodule
（2）一个workspace里面的多个crate是可以单独发布的，例如，单独指定版本，单独分享到crate.io中。

**Comment by liubaohai** [comment]
这样可以引入github中包
```
[dependencies.prometheus-static-metric]
git = "https://github.com/xx.git"
rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be"
```

**Comment by liubaohai** [comment]
每个`workspace`的`Cargo.toml`相互独立，可以定义自己的`dependencies`

**Comment by liubaohai** [comment]
代码的目录结构，每个目录创建一个`mod.rs`，里面声明提供给外部调用的mod

**Comment by liubaohai** [comment]
`src`目录提供一个`lib.rs`，这里面仅提供给集成测试、其它`workspace`、main函数调用的mod，为了整洁，逻辑实现不要放到这里。

**Comment by lishulong** [comment]
感觉咱们的项目里，除了celeritasDB之外，应该都是以lib的方式发布的吧
另外一个lib的crate也可以生成binary，只要在src/bin/下面创建一个xxx.rs，cargo build就能自动创建出binary。

所以综上，建议：
（1）统一一个Git repo，以workspace的方式组织代码库
（2）除celeritasDB之外，其他crate尽量使用cargo new xxx --lib的方式创建，如果需要生成binary，创建src/bin/xxx.rs 
（3）使用lib.rs 暴露整个crate对外接口，可以在此处定义最外层API实现。
（4）module级别的接口使用mod.rs暴露，mod.rs里不写实现，只是对外提供模块接口和数据结构。

**Comment by lishulong** [comment]
（5）main.rs里面只实现命令含参数解析和配置加载的工作，实际工作和核心API都放到lib.rs和其他module里。

**Comment by lishulong** [comment]
还是不太熟悉rust，大家商量一下吧

**Comment by liubaohai** [comment]
#    每个workspace的Cargo.toml相互独立，可以定义自己的dependencies

#    创建workspace遵循一个规则，我参考`tikv`的结构
-    `components`目录每个`workspace`是一个组件，以`lib`的方式
-    `cmd`目录`Cargo.toml`以`bin`的方式，所有的`bin`都放到这里
-    `src`目录提供一些公共的代码，这些不需要单独发布的

比如：
```
./Cargo.toml
./Cargo.lock
./cmd/Cargo.toml
./components/xx/Cargo.toml
```

**Comment by lishulong** [comment]
tikv是多个workspace的？

**Comment by pengsven** [comment]
> 感觉咱们的项目里，除了celeritasDB之外，应该都是以lib的方式发布的吧
> 另外一个lib的crate也可以生成binary，只要在src/bin/下面创建一个xxx.rs，cargo build就能自动创建出binary。
> 
> 所以综上，建议：
> （1）统一一个Git repo，以workspace的方式组织代码库

+1, 每个组件独立crate, 需要发布的crate, 在`<crate>/Cargo.toml`中配置发布信息
> （2）除celeritasDB之外，其他crate尽量使用cargo new xxx --lib的方式创建，如果需要生成binary，创建src/bin/xxx.rs

src/bin/xxx.rs怎么编译, 不建议这么组织代码, 独立执行的创建一个binary crate?
> （3）使用lib.rs 暴露整个crate对外接口，可以在此处定义最外层API实现。
> （4）module级别的接口使用mod.rs暴露，mod.rs里不写实现，只是对外提供模块接口和数据结构。

(3)和(4) 合并下? lib.rs定义整个crate对外的接口和数据结构, 再以mod组织具体实现代码

>（5）main.rs里面只实现命令含参数解析和配置加载的工作，实际工作和核心API都放到lib.rs和其他module里。
+1

 (6) 另外添加src/tests目录存放集成测试代码, 且每个create包含各自的测试文件 如xxx_test.rs

**Comment by lishulong** [comment]
@pengsven 
> （2）除celeritasDB之外，其他crate尽量使用cargo new xxx --lib的方式创建，如果需要生成binary，创建src/bin/xxx.rs
> src/bin/xxx.rs怎么编译, 不建议这么组织代码, 独立执行的创建一个binary crate?
直接在那个crate的目录下，cargo build 就可以了

**Comment by lishulong** [comment]
>3）使用lib.rs 暴露整个crate对外接口，可以在此处定义最外层API实现。
>（4）module级别的接口使用mod.rs暴露，mod.rs里不写实现，只是对外提供模块接口和数据结构。

>(3)和(4) 合并下? lib.rs定义整个crate对外的接口和数据结构, 再以mod组织具体实现代码

对，我也是这个意思，crate级别需要暴露的都在lib.rs里，module级别需要暴露的都放到mod.rs里。
即使是那种re-export的最好也能这样，每个级别对外都有一个统一的地方export

**Comment by drmingdrmer** [comment]
#13 中按照上面描述整理了一下, 还没有使用mod.rs, 大家看看没啥问题这个issue就可以关掉了

**Comment by drmingdrmer** [comment]
https://www.lucidchart.com/documents/view/68811c65-ff11-441c-822f-ff659190d747/AWJWbYUW9kzj
