### ISSUE TITLE
2019-12-27 讨论议题

### ISSUE THREAD

**Issue by lishulong** [openacid/celeritasdb#21]
### ![wenbo](https://avatars3.githubusercontent.com/u/11748387?s=40&v=4) 议题：
snapshot 功能和 epaxos crate 的相关性很高。但是之前 snapshot 是独立的 crate，是否保持独立？或者合并成 epaxos crate 的一个 mod。

### liubaohai
是否去掉`seq`？采用哪种方式？

**Comment by drmingdrmer** [comment]
### xp的:
去掉seq有点麻烦, 打算在这一版中只实现3节点的实现, 所有步骤都会简单很多.
seq的处理可以通过commit deps之后才允许commit instance来解决.

论文感觉没有什么不确定的内容了. 除了笔者文风挥洒不容易看懂.

**Comment by pengsven** [comment]
### yipu的:
- thrifty epaxos恢复流程的讨论

**Comment by lishulong** [comment]
lsl：

恢复流程整个过一遍。

**Comment by lishulong** [comment]
有必要的讨论，请记录到 wiki

https://github.com/openacid/celeritasdb/wiki/Discussion
