### ISSUE TITLE
execution顺序的疑问

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/celeritasdb#23]
某时刻某个replica上的部分instancespace如下:

```
|       .->d 
|      /   | 
b<-------->c 
a<----'    | 
|          | 
------------
```

`a, d` 是interfering的 2个instance, 互相依赖.
`b, c` 是interfering的 2个instance, 互相依赖.

> 例如a,d是set x的, b,c是set y的.

按照epaxos的描述, 以及代码实现来看, 似乎并没有保证这4个instance的总体顺序?
而只保证了`a,d`作为一个SCC的顺序, 和`b,c`作为一个SCC的顺序.

而`a,d`和`b,c`这2组谁先执行, 就看谁先commit了? 
例如像epaxos.go中429行开始的执行逻辑.

感觉这里有点问题啊, paper中的执行顺序是`ad 然后bc` 或`bc然后ad` 这2种情况, 都可能出现.
但是真实的时序有可能是`a,c,b,d` 这种顺序.
**也就是说d有可能先于c执行**, 感觉有点不合理. 但也没什么错误

**Comment by liubaohai** [comment]
```
-    a入栈

a DFN:1,LOW:1

-    c入栈，通过b先看到a，找到a的LOW=1

c DFN:2,LOW:1
a DFN:1,LOW:1

-    b入栈，通过b找到c的LOW=1

b DFN:3,LOW:1
c DFN:2,LOW:1
a DFN:1,LOW:1

-    d入栈，找到a的LOW=1

d DFN:4,LOW:1
b DFN:3,LOW:1
c DFN:2,LOW:1
a DFN:1,LOW:1

最终发现a的DFN=LOW，栈里面的abcd是一个SCC
```

**Comment by drmingdrmer** [comment]
@liubaohai 为啥又开了? 可以关了吧?

**Comment by drmingdrmer** [comment]
讨论结果: 应该将abcd看做一个SCC来处理一起执行.

**Comment by liubaohai** [comment]
@drmingdrmer 可以关了
