### ISSUE TITLE
有个关于fast-quorum=N-1的问题.

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/celeritasdb#24]
Assumes we have N=3 replicas thus:
quorum = ⌊N/2⌋ = 2
and fast-quorum = N-1 = 2

1. R1 received a request and initialized an instance `R1.a`. R2 received a request `R2.b`, R3 received a request `R3.c`.
2. R1 sent PreAccpet to R2 and R3.
3. Then R2 will store `R1.a depends on R2.b`.
    Then R3 will store `R1.a depends on R3.c`.

As you mentioned in #16 :
> Yes, allEqual is still necessary even if you don't use seq. That's necessary for correct recovery of a command committed on the fast path. However, allCommitted is no longer necessary.

4. Now R1 could commit `R1.a depends on R2.b` or `R1.a depends on R3.c`, depends on whose reply it received.

5. And now R1 powered off.
6. The recovery process will see two value `R1.a depends on R2.b` and `R1.a depends on R3.c`. Either of them could have been committed by R1, because including the leader of `R1.a`, R2 and R3 both could have formed a fast-quorum.

So my question is how the recovery process chooses a value to send Accept request?
In my option, the only way to prevent this to happen is to allow fast-commit only when all dependent instances are committed. But you said this is not necessary, that confused me. 

Since according to the recover algorithm, R is possible to see two values that both achieve `⌊N/2⌋` replies, if N=3.
![image](https://user-images.githubusercontent.com/44069/71560589-5dcf6780-2aa7-11ea-9bbb-47530fae5fec.png)

**Comment by pengsven** [comment]
> 3. The recovery process will see two value `R1.a depends on R2.b` and `R1.a depends on R3.c`. Either of them could have been committed by R1, because including the leader of `R1.a`, R2 and R3 both could have formed a fast-quorum.
> 

R1.a在第5步宕机，不会走fast-path提交，因为没有达到N-1个R返回OK且和自己的instance相等，而且肯定R1还没有发送phase2，不然R2和R3有一个能看见状态为accepted
既然走的是slow-path，那么恢复按照classic paxos恢复选择任意一个看到的instance都可以

**Comment by lishulong** [comment]
>4. Now R1 could commit R1.a depends on R2.b or R1.a depends on R3.c, depends on whose reply it received.

这一步，如果严格按照只发送到fast-quorum个replica的话，应该不会发生。
因为，R1发送PreAccept到N-1个replica，包括自己，在N=3的情况下，也就是只会发送给R2和R3中的一个，所以不会同时出现`R1.a depends on R2.b or R1.a depends on R3.c` 的情况。

例如，R1收到的reply看到了`R1.a depends on R2.b`，那么因为reply的deps和自己的不一样，所以就开始走slow-path，发送accept请求和commit请求。所以R3不会记录`R1.a depends on R3.c`，而应该在接下来的步骤里记录`R3.c depends on R1.a`

> 5. And now R1 powered off.

这时候，会触发recovery process的只有R2（因为只有它知道R1.a这个instance）。
然后它发送prepare到系统中所有的replica，R1没响应，R3会回复一个PrepareOK，应为R3第一次知道R1.a，所以没有ballot number。然后R2应该走34 行。

**Comment by lishulong** [comment]
换一种情况来说，R1将PreAccept发送到了所有的Replica上，此时会出现`R1.a depends on R2.b or R1.a depends on R3.c`的情况。
然后假设R2发起了recovery过程，那么因为R3记录的deps和R2的不同，所以R2应该会在R1.a上提交一个no-op

**Comment by lishulong** [comment]
> 既然走的是slow-path，那么恢复按照classic paxos恢复选择任意一个看到的instance都可以

这里感觉会提交no-op。
因为R2和R3都是pre-accept，但是它们的deps都不同，所以会走到36行。

感觉这个Prepare和经典的paxos的prepare不同，经典paxos会使用ballot number大的instance，但是这个epaxos的Prepare看起来不会覆盖自己记录的instance。
```
38: if epoch:b:Q is larger than the most recent ballot
number epoch:x:Y accepted for instance L:i then
39: reply PrepareOK(cmdsR[L][i];epoch:x:Y;L:i)
```

**Comment by drmingdrmer** [comment]
> > Now R1 could commit R1.a depends on R2.b or R1.a depends on R3.c, depends on whose reply it received.

> 这一步，如果严格按照只发送到fast-quorum个replica的话，应该不会发生。
因为，R1发送PreAccept到N-1个replica，包括自己，在N=3的情况下，也就是只会发送给R2和R3中的一个，所以不会同时出现R1.a depends on R2.b or R1.a depends on R3.c 的情况。

实现时必须考虑发到所有replica的情况吧. 否则发1个不成果就必须卡主不动了.

> 例如，R1收到的reply看到了R1.a depends on R2.b，那么因为reply的deps和自己的不一样，所以就开始走slow-path，发送accept请求和commit请求。所以R3不会记录R1.a depends on R3.c，而应该在接下来的步骤里记录R3.c depends on R1.a

问题是如果发给了R2但没收到应答, 就不敢动了.

> 换一种情况来说，R1将PreAccept发送到了所有的Replica上，此时会出现R1.a depends on R2.b or R1.a depends on R3.c的情况。
然后假设R2发起了recovery过程，那么因为R3记录的deps和R2的不同，所以R2应该会在R1.a上提交一个no-op

这时应该不会用noop. 刚看了论文... N=3时, 见到跟自己不同的值就不能commit fast. 跟N大于3不一样.
大于3时, 看到fast-quorum - 1个同样的值就可以了.

**Comment by lishulong** [comment]
根据handlePrepare 函数，和startRecoveryForInstance 函数的实现，
这个流程看起来应该是这样的：假设R2去recover。
（1）R2增加ballot number，并且保存到自己的cmd记录中。
（2）R2发送Prepare请求给R3。
（3）R3收到Prepare请求，更新自己cmd记录中的ballot，然后返回PrepareOk。
（4）然后R2走explicit Prepare的34行（因为这里没有任何preparepare的reply用的是default ballot）
