### ISSUE TITLE
instance_num 改下名字叫instance_offset咋样?

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/celeritasdb#26]
因为num读起来像是总数的意思. 
offset表示这个instance在instanceSpace中某个个leader下的偏移位置.对应数组下标的概念.

可选名字:
- instance_offset
- offset
- instOffset
- instIndex
- index
- idx
- position
- pos

PS. rust里变量命名啥风格? `instID` 还是 `inst_id`?

**Comment by pengsven** [comment]
idx +1

**Comment by lishulong** [comment]
变量是单词加下划线，类型是驼峰式的

**Comment by wenbobuaa** [comment]
inst_index

**Comment by lishulong** [comment]
idx +1

**Comment by liubaohai** [comment]
inst_idx

**Comment by drmingdrmer** [comment]
那idx吧~

**Comment by drmingdrmer** [comment]
@lishulong 好像是树龙相关的代码? 下次一起改了吧

**Comment by lishulong** [comment]
done
