### ISSUE TITLE
snapshot 模块的职责描述

### ISSUE THREAD

**Issue by wenbobuaa** [openacid/celeritasdb#4]
#### 1. 与外部的交互
a. executed 的 command 需要把它修改的 key 和 vlaue 更新到 snapshot;

b. client 需要读取某个 key 时，需要 snapshot 进行查找;

c. 已经 committed 的 log 需要更新到 snapshot;

d. 还没有 executed 的 command 对应的 log 外部能够全部读到；已经 executed 的 command 对应的 log 外部全部不能读到；

#### 2. 内部的规划
a.  对 key-value 和对 log 的存储采用 2 个独立的模块，交互也使用 2 套不同的接口。

b. 为了保证 1.d 的需求，必须记录已经存储的 log 中，哪些是已经 executed。而且必须与 execute 模块保持一致。这一步在 execute 模块写入它要更新的 key 的时候，同时记录这个 key 所关联的那些被 executed 的 log（事务进行）。

c. 对 log 的存储需要一个清理的机制（例如，每天删除一次），只能清理已经 executed 的日志。

**Comment by drmingdrmer** [comment]
> c. 已经 committed 的 log 需要更新到 snapshot;

committed更新到snapshot是什么意思?

**Comment by wenbobuaa** [comment]
> > c. 已经 committed 的 log 需要更新到 snapshot;
> 
> committed更新到snapshot是什么意思?

意思是，已经 committed 的 command，需要通过在 snapshot 里插入一条 log ，来持久化。

**Comment by drmingdrmer** [comment]
没committed的日志也需要持久化啊

**Comment by wenbobuaa** [comment]
> 没committed的日志也需要持久化啊

我需要再复习一下 epaxos，再来优化下这里的描述。

**Comment by wenbobuaa** [comment]
相关的规划，都加入到 `docs/snapshot/README.md` 中，不在这里讨论了。
