### ISSUE TITLE
Engine(snapshot) 需要提供事务

### ISSUE THREAD

**Issue by wenbobuaa** [openacid/celeritasdb#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
在 executor 写入 key-value 的时候会需要.

接口：
```
Engine.begin() -> tx: 开始一个事务；
tx.get_kv(key)
tx.get_kv_for_update(key): 得到的 key 不能被其他事务修改；
tx.set_kvs(keys, values, instances)
tx.commit()：提交一个事务；
```
**Describe alternatives you've considered**

**Additional context**

**Comment by liubaohai** [comment]
使用writebatch代替，先close了
